security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN
    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                    superadmin:
                        password: 'superadmin'
                        roles: ['ROLE_SUPER_ADMIN']
        fos_userbundle:
            id: fos_user.user_provider.username
    access_control:
        - { path: ^/api/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users, roles: ROLE_ADMIN }       
        - { path: /api/^, roles: IS_AUTHENTICATED_FULLY } # ToDo Change later to FULLY


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    #   LEXIC JWT AUTH  remove comment to turn on
    #
    #    api_login:
    #        pattern:  ^/api/auth/login
    #        stateless: true
    #        anonymous: true
    #        json_login:
    #            provider: chain_provider
    #            check_path:               /api/auth/login
    #            success_handler:          lexik_jwt_authentication.handler.authentication_success
    #            failure_handler:          lexik_jwt_authentication.handler.authentication_failure
    #        provider: chain_provider
        
    #    api:
    #        pattern: ^/api/*
    #        stateless: true
    #        anonymous: false
    #        provider: chain_provider
    #        guard:
    #            authenticators:
    #            - lexik_jwt_authentication.jwt_token_authenticator
        main:
            pattern: ^/
            form_login:
                provider: chain_provider
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: false
                default_target_path: admin_admin_index
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
            anonymous:    true